apiVersion:c
kind: Ingress
metadata:
  name: flask-app-ingress
spec:
  rules:
  - host: localhost #vérifie si le sous domaine fonctionne...
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-app-service
            port:
              number: 80

              192.168.59.100