name: Build and Push Docker image on merge to master

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: mrandrianasolo/api-minikube-ci:${{ github.sha }}

    - name: Run tests
      run: |
        docker run --rm mrandrianasolo/api-minikube-ci:${{ github.sha }} sh -c "\
        pip install -r requirements.txt"
#        &&         pytest --junitxml=results.xml"

#    - name: Upload test results
#      uses: actions/upload-artifact@v2
#      with:
#        name: test-results
#        path: results.xml

    - name: Generate Swagger documentation
      run: |
        docker run --rm -v ${{ github.workspace }}:/app mrandrianasolo/api-minikube-ci:${{ github.sha }} sh -c "\
        mkdir -p /app/docs && \
        flask swagger generate > /app/docs/index.html"

    - name: Deploy Swagger documentation to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs

    - name: Send Discord notification
      run: |
        curl -H "Content-Type: application/json" \
             -d "{\"content\": \"Build and deployment successful for commit ${{ github.sha }}!\"}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}

    - name: Log out from Docker Hub
      run: docker logout
