name: Build and Push Docker image on merge to main

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: > 
          --health-cmd="mysqladmin ping --silent" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/api-minikube-ci:${{ github.sha }}

    - name: Wait for MySQL to be ready
      run: |
        while ! docker exec $(docker ps -q --filter "ancestor=mysql:5.7") mysqladmin ping --silent; do
          echo "Waiting for MySQL..."
          sleep 2
        done

    - name: Run tests
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_USER: root
        DB_PASSWORD: root_password
        DB_NAME: test_db
      run: |
        docker run --rm -e DB_HOST -e DB_PORT -e DB_USER -e DB_PASSWORD -e DB_NAME -v ${{ github.workspace }}/test-reports:/test-reports ${{ secrets.DOCKER_USERNAME }}/api-minikube-ci:${{ github.sha }} sh -c "\
        pip install -r requirements.txt && \
        python -m unittest discover -s . -p 'test_app.py'"

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-reports/results.xml

    - name: Generate Swagger documentation
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_USER: root
        DB_PASSWORD: root_password
        DB_NAME: test_db
      run: |
        docker run --rm -e DB_HOST -e DB_PORT -e DB_USER -e DB_PASSWORD -e DB_NAME -v ${{ github.workspace }}:/app mrandrianasolo/api-minikube-ci:${{ github.sha }} sh -c "\
        mkdir -p /app/docs && \
        flask run --host=0.0.0.0 & sleep 10 && \
        wget -r -np -k -P /app/docs http://127.0.0.1:5000/apidocs/"

    - name: Deploy Swagger documentation to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs

    - name: Send Discord notification
      run: |
        curl -H "Content-Type: application/json" \
             -d "{\"content\": \"Build and deployment successful for commit ${{ github.sha }}!\"}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}

    - name: Log out from Docker Hub
      run: docker logout
